config/routes.rb
Mrhindicacao::Application.routes.draw do
  
  resources :indicacaos

  resources :servicos

  resources :clientes

  #resources :relatorios

  get "user/index"

  resources :roles

  resources :setors

  devise_for :users

  resources :user

  root :to => 'application#index'

  match "/user/criar_novo" => "user#criar_novo"
  #direciona para lista de clientes modal
  match "/cliente/index_modal" =>  "clientes#index_modal"
  #direciona para new cliente modal
  match "/cliente/novo_modal" => "clientes#novo_modal"
  #cria novo cliente pela janela modal
  match "/cliente/create_modal" => "clientes#create_modal"
  #enviar email das indicações marcadas
  match '/indicacao/enviar_email' => 'indicacaos#enviar_email'
  #filtro para relatório de indicações
  match '/relatorio/indicacoes_filtro' => 'relatorios#indicacoes_filtro'
  #relatório de indicações
  match 'relatorio/indicacoes' => 'relatorios#indicacoes'
  #exibir indicacoes fianlizadas
  match 'indicacoes/finalizadas' => 'indicacaos#finalizadas'

  
end

app/models/cliente.rb
#coding: utf-8
class Cliente < ActiveRecord::Base
  attr_accessible :contato, :email, :nome, :observacao, :telefone, :cnpj

  has_many :indicacaos,       :dependent => :restrict
  has_many :contato_clientes, :dependent => :restrict

  #validates :cnpj, :uniqueness => {:message => "JÁ EXISTE"}
  #validates :cnpj, :presence => {:message => "NÃO PODE ESTAR EM BRANCO"}
  validates :nome, :presence => {:message => "NÃO PODE ESTAR EM BRANCO"}
  
end

app/controllers/clientes_controller.rb
#coding: utf-8
class ClientesController < ApplicationController
  #load_and_authorize_resource
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  def index_modal
    @clientes = Cliente.all
    render :layout => false
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  def novo_modal
    @cliente = Cliente.new
    render layout: false
  end

  def create_modal
    cliente = Cliente.new(:nome => params[:nome],
     :cnpj => params[:cnpj],
     :contato => params[:contato], 
     :telefone => params[:telefone],
     :email => params[:email],
     :observacao => params[:observacao])
    cliente.save
    render json: cliente

  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])
    respond_to do |format|
      if @cliente.save
        if params[:contato]
          params[:contato].each do |i, contato|
            contatoCliente            = ContatoCliente.new
            contatoCliente.cliente_id = @cliente.id
            contatoCliente.nome       = contato[:nome]
            contatoCliente.fone       = contato[:fone]
            contatoCliente.save 
          end
        end
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        @cliente.contato_clientes.destroy

        if params[:contato]
          params[:contato].each do |i, contato|
            contatoCliente            = ContatoCliente.new
            contatoCliente.cliente_id = @cliente.id
            contatoCliente.nome       = contato[:nome]
            contatoCliente.fone       = contato[:fone]
            contatoCliente.save
          end
        end
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    begin
      @cliente.destroy
    rescue ActiveRecord::DeleteRestrictionError => e
      flash[:error] = 'Cliente não pode ser excluído. Existem indicaçãoes para ele'
    end

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    Contato<input type='button' value='Novo' onclick='adicionaContato();'><br />
      <% @cliente.contato_clientes.each do |cc| %>
        Nome: <%= cc.nome %> - Fone: <%= cc.fone %>
      <% end %>
    <div id="novo_contato">
    </div>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    Contato:
    <%= f.label :observacao %><br />
    <%= f.text_area :observacao, :size => "30x10" %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type='text/javascript'>

var contato = 0;
var adicionaContato = function(){
  $('#novo_contato').html($('#novo_contato').html() + "<input type='text' name='contato["+ contato +"][nome]'> - <input type='text' name='contato["+ contato +"][fone]'></br>");
  contato++;
}

</script>

app/views/clientes/edit.html.erb
<h3>Alterando Cliente</h3>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h3>Clientes</h3>
<a href="/clientes/new"><button class='btn'>Novo Cliente</button></a><br><br>

<table id="clientes_tab" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj</th>
      <th>Contato</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Observacao</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.cnpj %></td>
    <td><%= cliente.contato %></td>
    <td><%= cliente.telefone %></td>
    <td><%= cliente.email %></td>
    <td><%= cliente.observacao %></td>
    <td>
      <%= link_to 'Exibir', cliente %>
      <%= link_to 'Alterar', edit_cliente_path(cliente) %>
      <%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Deseja realmente apagar?' } %>
    </td>
  </tr>
  <% end %>
  </tbody>

</table>

<br />



<script type="text/javascript">
  $(document).ready(function(){
    $('#clientes_tab').dataTable({
       "oLanguage": {
      "sLengthMenu": "_MENU_ registros por página",
      "sZeroRecords": "Nenhum registro",
      "sInfo": "Exibindo _START_ de _END_ total _TOTAL_ registros",
      "sInfoEmpty": "Exibindo 0 de 0 de 0 registros",
      "sInfoFiltered": "(filtered from _MAX_ total records)"
    }
    });
  });

</script>

app/views/clientes/index_modal.html.erb
<%= stylesheet_link_tag "DT_bootstrap" %>
<%= javascript_include_tag "DT_bootstrap" %>
<%= javascript_include_tag "jquery.dataTables.min" %>

<table id="clientes" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Nome</th>
    <th>CNPJ</th>
    <th>Contato</th>
    <th>Telefone</th>
    <th>inserir</th>
  </tr>
  </thead>
  <tbody>
<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.cnpj %></td>
    <td><%= cliente.contato %></td>
    <td><%= cliente.telefone %></td>
    <td><input type="button" value='selecionar', onclick="selecionar_cliente(<%= [cliente.id, cliente.nome] %>)" /></td>
  </tr>
<% end %>
  </tbody>
</table>
<script type="text/javascript">
  $(function(){
    $('#clientes').dataTable();
  });

  var selecionar_cliente = function(cliente){
    $("#indicacao_cliente_id").val(cliente[0]);
    $("#cliente_nome").val(cliente[1]);
    $('#modalPesquisa').modal('hide')
  }
</script>

app/views/clientes/new.html.erb
<h3>Novo cliente</h3>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/novo_modal.html.erb
<%= form_tag "/cliente/create_modal", :method => 'post' do %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <td><%= label_tag :nome %></td>
    <td><%= text_field_tag :nome %></td>
  </tr>
   <tr>
    <td><%= label_tag :cnpj %></td>
    <td><%= text_field_tag :cnpj %></td>
  </tr>
  <tr>
    <td><%= label_tag :contato %></td>
    <td><%= text_field_tag :contato %></td>
  </tr>
  <tr>
    <td><%= label_tag :telefone %></td>
    <td><%= text_field_tag :telefone %></td>
  </tr>
  <tr>
    <td><%= label_tag :email %></td>
    <td><%= text_field_tag :email %></td>
  </tr>
  <tr>
    <td><%= label_tag :observacao %></td>
    <td><%= text_area_tag :observacao %></td>
  </tr>
  <tr>
  <div class="actions">
    <td><input type="button" value='Cadastrar' onclick="cadastrar()" %></td>
  </div>
</tr>
<% end %>
<script type="text/javascript">
  var cadastrar = function(){
    var nome = $("#nome").val();
    var contato = $("#contato").val();
    var telefone = $("#telefone").val();
    var email = $("#email").val();
    var observacao = $("observacao").val();
    $.post(
      "/cliente/create_modal",
      {nome:nome, contato:contato, telefone:telefone, email:email, observacao:observacao},
      function(retorno){
        $("#indicacao_cliente_id").val(retorno.id);
        $("#cliente_nome").val(retorno.nome);
        $('#modalNovo').modal('hide')
      }
      )
  }
</script>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Contato:</b>
  <%= @cliente.contato %>
</p>

<p>
  <b>Telefone:</b>
  <%= @cliente.telefone %>
</p>

<p>
  <b>Email:</b>
  <%= @cliente.email %>
</p>

<p>
  <b>Observacao:</b>
  <%= @cliente.observacao %>
</p>


<%= link_to 'Alterar', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %>