config/routes.rb
Mrhindicacao::Application.routes.draw do
  
  resources :indicacaos

  resources :servicos

  resources :clientes

  #resources :relatorios

  get "user/index"

  resources :roles

  resources :setors

  devise_for :users

  resources :user

  root :to => 'application#index'

  match "/user/criar_novo" => "user#criar_novo"
  #direciona para lista de clientes modal
  match "/cliente/index_modal" =>  "clientes#index_modal"
  #direciona para new cliente modal
  match "/cliente/novo_modal" => "clientes#novo_modal"
  #cria novo cliente pela janela modal
  match "/cliente/create_modal" => "clientes#create_modal"
  #enviar email das indicações marcadas
  match '/indicacao/enviar_email' => 'indicacaos#enviar_email'
  #filtro para relatório de indicações
  match '/relatorio/indicacoes_filtro' => 'relatorios#indicacoes_filtro'
  #relatório de indicações
  match 'relatorio/indicacoes' => 'relatorios#indicacoes'
  #exibir indicacoes fianlizadas
  match 'indicacoes/finalizadas' => 'indicacaos#finalizadas'

  
end

app/models/setor.rb
class Setor < ActiveRecord::Base
  has_many :users
  attr_accessible :descricao

end

app/controllers/setors_controller.rb
class SetorsController < ApplicationController
load_and_authorize_resource
  # GET /setors
  # GET /setors.json
  def index
    @setors = Setor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @setors }
    end
  end

  # GET /setors/1
  # GET /setors/1.json
  def show
    @setor = Setor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setor }
    end
  end

  # GET /setors/new
  # GET /setors/new.json
  def new
    @setor = Setor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setor }
    end
  end

  # GET /setors/1/edit
  def edit
    @setor = Setor.find(params[:id])
  end

  # POST /setors
  # POST /setors.json
  def create
    @setor = Setor.new(params[:setor])

    respond_to do |format|
      if @setor.save
        format.html { redirect_to @setor, notice: 'Setor was successfully created.' }
        format.json { render json: @setor, status: :created, location: @setor }
      else
        format.html { render action: "new" }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /setors/1
  # PUT /setors/1.json
  def update
    @setor = Setor.find(params[:id])

    respond_to do |format|
      if @setor.update_attributes(params[:setor])
        format.html { redirect_to @setor, notice: 'Setor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setors/1
  # DELETE /setors/1.json
  def destroy
    @setor = Setor.find(params[:id])
    @setor.destroy

    respond_to do |format|
      format.html { redirect_to setors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/setors_helper.rb
module SetorsHelper
end

app/views/setors/_form.html.erb
<%= form_for(@setor) do |f| %>
  <% if @setor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setor.errors.count, "error") %> prohibited this setor from being saved:</h2>

      <ul>
      <% @setor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setors/edit.html.erb
<h1>Editing setor</h1>

<%= render 'form' %>

<%= link_to 'Show', @setor %> |
<%= link_to 'Back', setors_path %>

app/views/setors/index.html.erb
<h3>Setores</h3>
<p>
<%= link_to 'Novo Setor', new_setor_path %>
</p>
<table id="table" class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Descricao</th>
    <th>Exibir</th>
    <th>Alterar</th>
    <th>Apagar</th>
  </tr>
</thead>
<tbody>
<% @setors.each do |setor| %>
  <tr>
    <td><%= setor.descricao %></td>
    <td><%= link_to 'Exibir', setor %></td>
    <td><%= link_to 'Editar', edit_setor_path(setor) %></td>
    <td><%= link_to 'Apagar', setor, method: :delete, data: { confirm: 'Confirma exclusão?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<script type="text/javascript">
  $(document).ready(function(){
    $('#table').dataTable({
    "oLanguage": {
      "sLengthMenu": "_MENU_ registros por página",
      "sZeroRecords": "Nenhum registro",
      "sInfo": "Exibindo _START_ de _END_ total _TOTAL_ registros",
      "sInfoEmpty": "Exibindo 0 de 0 de 0 registros",
      "sInfoFiltered": "(filtered from _MAX_ total records)"
    }
  });
  });

</script>

app/views/setors/new.html.erb
<h3>Novo setor</h3>

<%= render 'form' %>

<%= link_to 'Back', setors_path %>

app/views/setors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descricao:</b>
  <%= @setor.descricao %>
</p>


<%= link_to 'Edit', edit_setor_path(@setor) %> |
<%= link_to 'Back', setors_path %>