config/routes.rb
Mrhindicacao::Application.routes.draw do
  
  resources :indicacaos

  resources :servicos

  resources :clientes

  #resources :relatorios

  get "user/index"

  resources :roles

  resources :setors

  devise_for :users

  resources :user

  root :to => 'application#index'

  match "/user/criar_novo" => "user#criar_novo"
  #direciona para lista de clientes modal
  match "/cliente/index_modal" =>  "clientes#index_modal"
  #direciona para new cliente modal
  match "/cliente/novo_modal" => "clientes#novo_modal"
  #cria novo cliente pela janela modal
  match "/cliente/create_modal" => "clientes#create_modal"
  #enviar email das indicações marcadas
  match '/indicacao/enviar_email' => 'indicacaos#enviar_email'
  #filtro para relatório de indicações
  match '/relatorio/indicacoes_filtro' => 'relatorios#indicacoes_filtro'
  #relatório de indicações
  match 'relatorio/indicacoes' => 'relatorios#indicacoes'
  #exibir indicacoes fianlizadas
  match 'indicacoes/finalizadas' => 'indicacaos#finalizadas'

  
end

app/models/servico.rb
#coding: utf-8
class Servico < ActiveRecord::Base
  attr_accessible :descricao, :porcentagem, :email, :detalhes, :comissao_valor

   validates :email,    :presence => {:message => "não pode ficar em branco."}

end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  load_and_authorize_resource 
  # GET /servicos
  # GET /servicos.json
  def index
    @servicos = Servico.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servicos }
    end
  end

  # GET /servicos/1
  # GET /servicos/1.json
  def show
    @servico = Servico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @servico }
    end
  end

  # GET /servicos/new
  # GET /servicos/new.json
  def new
    @servico = Servico.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @servico }
    end
  end

  # GET /servicos/1/edit
  def edit
    @servico = Servico.find(params[:id])
  end

  # POST /servicos
  # POST /servicos.json
  def create
    @servico = Servico.new(params[:servico])

    respond_to do |format|
      if @servico.save
        format.html { redirect_to @servico, notice: 'Servico was successfully created.' }
        format.json { render json: @servico, status: :created, location: @servico }
      else
        format.html { render action: "new" }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servicos/1
  # PUT /servicos/1.json
  def update
    @servico = Servico.find(params[:id])

    respond_to do |format|
      if @servico.update_attributes(params[:servico])
        format.html { redirect_to @servico, notice: 'Servico was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicos/1
  # DELETE /servicos/1.json
  def destroy
    @servico = Servico.find(params[:id])
    @servico.destroy

    respond_to do |format|
      format.html { redirect_to servicos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/servicos/_form.html.erb
<%= form_for(@servico) do |f| %>
  <% if @servico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servico.errors.count, "error") %> prohibited this servico from being saved:</h2>

      <ul>
      <% @servico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="float: left">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field" style="float: left">
    <%= f.label :comissão_porcentagem %><br />
    <%= f.text_field :porcentagem %>
  </div>
  <div class="field">
    <%= f.label :comissão_valor %><br />
    <%= f.text_field :comissao_valor %>
  </div>
  <div class="field">
    <%= f.label :detalhes %><br />
    <%= f.text_area :detalhes, :style => "width: 458px; height: 139px;" %>
  </div>
  <div class="actions">
    <%= f.submit 'Criar Serviço'%>
  </div>
<% end %>

app/views/servicos/edit.html.erb
<h3>Alterar Serviço</h2>

<%= render 'form' %>

<%= link_to 'Exibir', @servico %> |
<%= link_to 'Voltar', servicos_path %>

app/views/servicos/index.html.erb
<h1>Listing servicos</h1>

<table id="table" class="table table-striped table-bordered">
<thead>
  <tr>
    <th>Descricao</th>
    <th>Porcentagem</th>
    <th>Valor</th>
    <th>Exibir</th>
    <th>Alterar</th>
    <th>Apagar</th>
  </tr>
</thead>
<tbody><% @servicos.each do |servico| %>
  <tr>
    <td><%= servico.descricao %></td>
    <td><%= servico.porcentagem %></td>
    <td><%= servico.comissao_valor %></td>
    <td><%= link_to 'Show', servico %></td>
    <td><%= link_to 'Alterar', edit_servico_path(servico) %></td>
    <td><%= link_to 'Apagar', servico, method: :delete, data: { confirm: 'Deseja realmente apagar?' } %></td>
  </tr>
<% end %>
</table>
</tbody>


<br />

<%= link_to 'Novo Servico', new_servico_path %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#table').dataTable({
      "oLanguage": {
        "sLengthMenu": "_MENU_ registros por página",
        "sZeroRecords": "Nenhum registro",
        "sInfo": "Exibindo _START_ de _END_ total _TOTAL_ registros",
        "sInfoEmpty": "Exibindo 0 de 0 de 0 registros",
        "sInfoFiltered": "(filtered from _MAX_ total records)"
      }
    });
  });

</script>

app/views/servicos/new.html.erb
<h4>Novo serviço</h4>

<%= render 'form' %>

<%= link_to 'Voltar', servicos_path %>

app/views/servicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descricao:</b>
  <%= @servico.descricao %>
</p>

<p>
  <b>Porcentagem:</b>
  <%= @servico.porcentagem %>
</p>


<%= link_to 'Edit', edit_servico_path(@servico) %> |
<%= link_to 'Back', servicos_path %>